name: Deploy Front End to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy front end files to Azure VM
        env:
          SSHPASS: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          # Ensure the target directory exists on the VM
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} "mkdir -p /home/${{ secrets.AZURE_VM_USERNAME }}/frontend"
          
          # Copy all files from the current directory to the target directory on the VM
          sshpass -e scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }}:/home/${{ secrets.AZURE_VM_USERNAME }}/frontend

      - name: Create .env file for front end on Azure VM
        env:
          SSHPASS: ${{ secrets.AZURE_VM_PASSWORD }}
          FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}
        run: |
          # Connect to the VM and create the .env file in the frontend directory
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} "echo \"$FRONTEND_ENV\" > /home/${{ secrets.AZURE_VM_USERNAME }}/frontend/.env"

      - name: SSH into Azure VM and deploy front end with Docker
        env:
          SSHPASS: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          # SSH into the VM and deploy the Docker container
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
            cd /home/${{ secrets.AZURE_VM_USERNAME }}/frontend

            # Cleanup unused Docker resources
            sudo docker system prune -a --volumes -f

            # Stop and remove the existing container if it exists
            sudo docker stop ForstAIfe || true && sudo docker rm ForstAIfe || true

            # Build and run the new container
            sudo docker build -t ForstAIfe .
            sudo docker run -d --restart=always -p 3000:3000 --name ForstAIfe ForstAIfe
          EOF
